services:
  freeradius-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - radiusdb
    restart: always
    volumes:
      - ./raddb/mods-available/sql:/etc/raddb/mods-available/sql
    ports:
      - 11812-11813:1812-1813/udp
    command: radiusd -X
    healthcheck:
      test: ["CMD", "radiusd", "-XC"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - rad-net
    logging:
      options:
         max-size: "50M"
         max-file: "1"

  radiusdb:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin@dev
      MARIADB_DATABASE: radius
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306
    networks:
      - rad-net

networks:
  rad-net: